### ISSUE TITLE
Help with configuration.

### ISSUE THREAD

**Issue by codybuell** [alibenpeng/ppm2crazyflie#2]
I'm trying to connect a Taranis x9d plus to the Crazyflie 1.0.  Code compiles and deploys to the Arduino Uno cleanly, serial output shows a good connection to the Crazyflie, leds also indicate so, but any input from the radio has no effect on the quad.  Do you have any more notes on configuration or direction to take for troubleshooting?  If you are able to help out let me know what info I can provide.  Thanks for your work on this!

**Comment by alibenpeng** [comment]
Sounds like either disarmed or no PPM input at all. Do you have any way of verifying if there actually is a PPM input on pin PB0 (D8 in *duino-speak)? If it is, make sure you have your channels in the RX set up right. I don't know the Taranis, so I can't help with that.

**Comment by codybuell** [comment]
Turns out that the crazyflie was not configured properly and there was some interference on the selected channel.  I had to upgrade the crazyflie firmware (likely didn't have any effect), set its radio bandwidth from 250Kbps to 1 MBps, and adjust the channel.  Is that expected?  Anyway, put it all on an Arduino pro mini inside a blank JR module and it works great!  Thanks for your work on this!
